In [2]:
import numpy as np

In [3]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
a1=np.array([3,4,5,6,7])
a2=np.array([1,2,3,4,5,])

In [6]:
a1+a2

array([ 4,  6,  8, 10, 12])

In [10]:
a3=np.array([3,4,5,6,7,8])
a4=np.array([1,2,3,4,5,])

In [11]:
a3+a4

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [13]:
a1*a2

array([ 3,  8, 15, 24, 35])

In [14]:
a1/a2

array([3.        , 2.        , 1.66666667, 1.5       , 1.4       ])

In [16]:
a5=np.array([[3,4,5], [6,7,8]])
a6=np.array([[1,2,3], [4,5,6]])

In [17]:
a5

array([[3, 4, 5],
       [6, 7, 8]])

In [18]:
a6

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a5+a6

array([[ 4,  6,  8],
       [10, 12, 14]])

In [20]:
a5*a6

array([[ 3,  8, 15],
       [24, 35, 48]])

In [21]:
a5/a6

array([[3.        , 2.        , 1.66666667],
       [1.5       , 1.4       , 1.33333333]])

In [26]:
a7 = np.array([[2,3], [1,2]])
a8 = np.array([[1,2], [2,3]])

In [23]:
a7+a8

array([[3, 5],
       [3, 5]])

In [24]:
a7*a8

array([[2, 6],
       [2, 6]])

In [27]:
a7@a8

array([[ 8, 13],
       [ 5,  8]])

In [29]:
np.dot(a7,a8)

array([[ 8, 13],
       [ 5,  8]])