In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
import joblib

c:\Users\Joejoyal\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
c:\Users\Joejoyal\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
from sklearn.datasets import load_iris

In [3]:
data =load_iris()

In [7]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [12]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [11]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
df['target'] = data.target

In [14]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
df['target_name'] = df['target'].map({i:name for i, name in enumerate(data.target_names)})

In [19]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [21]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int32
target_name           object
dtype: object

In [24]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_name          0
dtype: int64

In [25]:
df['target_name'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: target_name, dtype: int64

In [27]:
binary_df = df[df['target'] !=2]

In [29]:
binary_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target target_name  
0       0      setosa  
1       0      setosa  
2       0      setosa  
3       0      setosa  
4       0      setosa

In [42]:
x_binary = binary_df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

In [43]:
x_binary

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [44]:
y_binary = binary_df[['target']]

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x_binary, y_binary, test_size= .2)

In [46]:
x_train.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count          80.000000         80.000000          80.000000   
mean            5.455000          3.086250           2.816250   
std             0.653307          0.449118           1.452318   
min             4.300000          2.000000           1.000000   
25%             5.000000          2.800000           1.400000   
50%             5.400000          3.050000           1.900000   
75%             5.900000          3.400000           4.300000   
max             7.000000          4.000000           4.900000   

       petal width (cm)  
count         80.000000  
mean           0.767500  
std            0.560238  
min            0.100000  
25%            0.200000  
50%            0.450000  
75%            1.300000  
max            1.800000

In [47]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

In [48]:
x_test = scaler.transform(x_test)

In [49]:
x_train

array([[-1.31698311,  0.25487197, -0.98131805, -1.01935257],
       [ 2.07174536, -0.6413811 ,  1.37453816,  1.13610661],
       [-1.00891688,  0.0308087 , -0.84273827, -1.01935257],
       [-1.31698311,  0.0308087 , -0.91202816, -1.01935257],
       [-1.00891688, -0.19325457, -0.98131805, -0.83973098],
       [ 1.91771225,  0.0308087 ,  1.09737861,  1.13610661],
       [-0.70085066,  0.92706177, -1.05060793, -0.83973098],
       [-0.39278444,  0.7029985 , -0.98131805, -1.01935257],
       [-0.08471821,  0.7029985 , -0.91202816, -0.66010938],
       [-0.54681755, -1.3135709 ,  0.12732017,  0.59724182],
       [ 0.68544735, -0.19325457,  0.95879883,  1.31572821],
       [-0.54681755,  0.47893523, -0.77344838, -0.48048778],
       [ 0.99351357, -0.6413811 ,  1.30524827,  0.77686342],
       [-0.70085066, -0.19325457, -0.84273827, -1.01935257],
       [-0.08471821,  1.82331483, -0.77344838, -0.66010938],
       [-1.00891688,  0.7029985 , -0.84273827, -1.01935257],
       [ 0.37738112,  1.

In [50]:
svm_binary = SVC(kernel='linear', C=1.0, probability=True)

In [51]:
svm_binary.fit(x_train, y_train)

c:\Users\Joejoyal\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [52]:
svm_binary.predict(x_test)

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [54]:
print("Binary class classification report:\n", classification_report(y_test, svm_binary.predict(x_test)))

Binary class classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [55]:
confusion_matrix(y_test, svm_binary.predict(x_test))

array([[ 9,  0],
       [ 0, 11]], dtype=int64)

In [56]:
joblib.dump(svm_binary, 'svm_binary.pkl')

['svm_binary.pkl']

In [57]:
x_multi = df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]

In [58]:
x_multi

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [59]:
y_multi = df['target']

In [60]:
y_multi

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [62]:
x_train_multi, x_test_multi, y_trian_multi, y_test_multi = train_test_split(x_multi, y_multi, test_size= .2)

In [63]:
svm_multi = SVC(kernel='linear')

In [64]:
svm_multi.fit(x_train_multi, y_trian_multi)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [65]:
svm_multi.predict(x_test_multi)

array([2, 1, 2, 1, 2, 0, 1, 1, 1, 2, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 2, 1,
       0, 1, 2, 1, 1, 1, 2, 1])

In [67]:
print(" report for multi class svc :\n", classification_report(y_test_multi, svm_multi.predict(x_test_multi)))

 report for multi class svc :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.93      0.88      0.90        16
           2       0.78      0.88      0.82         8

    accuracy                           0.90        30
   macro avg       0.90      0.92      0.91        30
weighted avg       0.91      0.90      0.90        30



In [68]:
confusion_matrix(y_test_multi, svm_multi.predict(x_test_multi))

array([[ 6,  0,  0],
       [ 0, 14,  2],
       [ 0,  1,  7]], dtype=int64)

In [69]:
joblib.dump(svm_multi, 'svm_multi.pkl')

['svm_multi.pkl']

In [ ]:
### Logistics pratical

In [70]:
x_train, x_test, y_train, y_test

(array([[-1.31698311,  0.25487197, -0.98131805, -1.01935257],
        [ 2.07174536, -0.6413811 ,  1.37453816,  1.13610661],
        [-1.00891688,  0.0308087 , -0.84273827, -1.01935257],
        [-1.31698311,  0.0308087 , -0.91202816, -1.01935257],
        [-1.00891688, -0.19325457, -0.98131805, -0.83973098],
        [ 1.91771225,  0.0308087 ,  1.09737861,  1.13610661],
        [-0.70085066,  0.92706177, -1.05060793, -0.83973098],
        [-0.39278444,  0.7029985 , -0.98131805, -1.01935257],
        [-0.08471821,  0.7029985 , -0.91202816, -0.66010938],
        [-0.54681755, -1.3135709 ,  0.12732017,  0.59724182],
        [ 0.68544735, -0.19325457,  0.95879883,  1.31572821],
        [-0.54681755,  0.47893523, -0.77344838, -0.48048778],
        [ 0.99351357, -0.6413811 ,  1.30524827,  0.77686342],
        [-0.70085066, -0.19325457, -0.84273827, -1.01935257],
        [-0.08471821,  1.82331483, -0.77344838, -0.66010938],
        [-1.00891688,  0.7029985 , -0.84273827, -1.01935257],
        

In [71]:
x_train_multi, x_test_multi, y_trian_multi, y_test_multi

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 8                  4.4               2.9                1.4               0.2
 9                  4.9               3.1                1.5               0.1
 54                 6.5               2.8                4.6               1.5
 17                 5.1               3.5                1.4               0.3
 72                 6.3               2.5                4.9               1.5
 ..                 ...               ...                ...               ...
 105                7.6               3.0                6.6               2.1
 128                6.4               2.8                5.6               2.1
 21                 5.1               3.7                1.5               0.4
 2                  4.7               3.2                1.3               0.2
 102                7.1               3.0                5.9               2.1
 
 [120 rows x 4 columns],
      sepal length (cm)  

In [72]:
from sklearn.linear_model import LogisticRegression

In [74]:
x_train

array([[-1.31698311,  0.25487197, -0.98131805, -1.01935257],
       [ 2.07174536, -0.6413811 ,  1.37453816,  1.13610661],
       [-1.00891688,  0.0308087 , -0.84273827, -1.01935257],
       [-1.31698311,  0.0308087 , -0.91202816, -1.01935257],
       [-1.00891688, -0.19325457, -0.98131805, -0.83973098],
       [ 1.91771225,  0.0308087 ,  1.09737861,  1.13610661],
       [-0.70085066,  0.92706177, -1.05060793, -0.83973098],
       [-0.39278444,  0.7029985 , -0.98131805, -1.01935257],
       [-0.08471821,  0.7029985 , -0.91202816, -0.66010938],
       [-0.54681755, -1.3135709 ,  0.12732017,  0.59724182],
       [ 0.68544735, -0.19325457,  0.95879883,  1.31572821],
       [-0.54681755,  0.47893523, -0.77344838, -0.48048778],
       [ 0.99351357, -0.6413811 ,  1.30524827,  0.77686342],
       [-0.70085066, -0.19325457, -0.84273827, -1.01935257],
       [-0.08471821,  1.82331483, -0.77344838, -0.66010938],
       [-1.00891688,  0.7029985 , -0.84273827, -1.01935257],
       [ 0.37738112,  1.

In [76]:
logistics_binary = LogisticRegression()
logistics_binary.fit(x_train, y_train)

c:\Users\Joejoyal\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [77]:
logistics_binary.predict(x_test)

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1])

In [79]:
print(classification_report(y_test, logistics_binary.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [80]:
confusion_matrix(y_test, logistics_binary.predict(x_test))

array([[ 9,  0],
       [ 0, 11]], dtype=int64)

In [81]:
joblib.dump(logistics_binary, "logistics_binary.pkl")

['logistics_binary.pkl']

In [ ]:
x_train_multi, x_test_multi, y_trian_multi, y_test_multi

In [ ]:
x_train_multi

In [84]:
logistics_ovr = LogisticRegression(multi_class='ovr',solver='lbfgs',max_iter=2000)

In [85]:
logistics_ovr

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [86]:
logistics_ovr.fit(x_train_multi, y_trian_multi)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [87]:
logistics_ovr.predict(x_test_multi)

array([2, 1, 2, 2, 2, 0, 1, 1, 1, 2, 1, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1,
       0, 1, 2, 2, 1, 1, 2, 1])

In [89]:
print("classification report for ovr logistics", classification_report(y_test_multi, logistics_ovr.predict(x_test_multi)))

classification report for ovr logistics               precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       0.92      0.69      0.79        16
           2       0.58      0.88      0.70         8

    accuracy                           0.80        30
   macro avg       0.83      0.85      0.83        30
weighted avg       0.84      0.80      0.81        30



In [90]:
confusion_matrix(y_test_multi, logistics_ovr.predict(x_test_multi))

array([[ 6,  0,  0],
       [ 0, 11,  5],
       [ 0,  1,  7]], dtype=int64)

In [ ]:
logistics_multinomial = LogisticRegression(multi_class='multinomial',solver='lbfgs',max_iter=2000)

In [91]:
logistics_multinomial.fit(x_train_multi,y_trian_multi)

NameError: name 'logistics_multinomial' is not defined