In [15]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm
import statistics as stats

In [16]:
data = np.linspace(0,10,10000)

In [56]:
data1 = np.random.randn(10000)

In [57]:
data1

array([-0.65514991, -0.71314976, -0.96063208, ..., -0.06731268,
        0.5592881 ,  1.35071262])

In [17]:
data

array([0.00000000e+00, 1.00010001e-03, 2.00020002e-03, ...,
       9.99799980e+00, 9.99899990e+00, 1.00000000e+01])

In [18]:
np.mean(data)

5.0

In [19]:
np.median(data)

5.0

In [20]:
stats.mode(data)

StatisticsError: no unique mode; found 10000 equally common values

In [61]:
np.std(data1)

1.0035510812711623

In [62]:
norm.pdf(data1)

array([0.32188877, 0.30936613, 0.25149164, ..., 0.3980395 , 0.34118169,
       0.16022907])

In [63]:
plt.figure(figsize=(10,10))

<Figure size 1000x1000 with 0 Axes>

In [ ]:
plt.plot(data,norm.pdf(data1))

In [ ]:
!pip install statistics